### ISSUE TITLE
remove symbolic link

### ISSUE THREAD

**Issue by grotius-cnc** [DjangoReinhard/DxfView#1]
Hi,

Please remove the libdxfrw symbolic link and replace it with the libdxfrw  dir + files.

Then : 
../DxfView/dx_data.cpp:30:19: error: ‘class DRW_Entity’ has no member named ‘type’
   30 |   switch (entity->type()) {
      |                   ^~~~

**Comment by DjangoReinhard** [comment]
Thank you for that valuable feedback.
I fixed it and I hope, it works now

**Comment by grotius-cnc** [comment]
Ok see pull request.
Apps compiles and run when pull request is done.

**Comment by grotius-cnc** [comment]
Solved
